name: test-suite
on:
  push:
    branches:
      - master
      - dev
jobs:
  test-suite:
    name: test-suite
    runs-on: ubuntu-latest

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 6
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 16.1.0
    - name: Install dependencies
      run: npm install
    - name: Lerna bootstrap
      run: npm run boot -- --ci
    - name: Build project
      run: npm run build
    - name: Test
      run: npm test

    # - name: Publish if version has been updated
    #   uses: endel/npm-publish-action@master
    #   with:
    #     tag_name: "%s"
    #     tag_message: "v%s"
    #     commit_pattern: "^bump (\\S+)"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


